CREATE TABLE tbl_BOARD(
	bno NUMBER(10,0) PRIMARY KEY,
	TITLE VARCHAR2(200) NOT NULL,
	CONTENT VARCHAR2(2000) NOT NULL,
	WRITER VARCHAR2(50) NOT NULL,
	REGDATE DATE DEFAULT SYSDATE,
	UPDATEDATE DATE DEFAULT SYSDATE	
);

CREATE SEQUENCE SEQ_BOARD START WITH 1 INCREMENT BY 1

SELECT * FROM tbl_board

INSERT INTO tbl_board(bno, title, content, writer)
VALUES (seq_board.nextval, '테스트 제목','테스트 내용','user00')